"""Added guid_user table

Revision ID: 78089b94d5c0
Revises: 
Create Date: 2019-02-11 15:53:15.597859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy_utils import UUIDType

# revision identifiers, used by Alembic.
revision = '78089b94d5c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'guid_user',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('guid', UUIDType(), nullable=True),
        sa.Column('name', sa.Unicode(length=255), nullable=False),
        sa.Column('address', mysql.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('guid'),
    )
    op.create_index(op.f('ix_guid_user_id'), 'guid_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guid_user_id'), table_name='guid_user')
    op.drop_table('guid_user')
    # ### end Alembic commands ###
